apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: pihole.pgorzynski.pl
    http:
      paths:
      - path:
        backend:
          serviceName: pihole-service
          servicePort: 80