---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-etc
spec:
  accessModes:
    - ReadWriteMany              # define how volume should be mounted on host (ReadOnlyMany , readWriteOnce, ReadWriteMany)
  capacity:
    storage: 1Gi
  hostPath:                     # volume path on host ( do not used in prod as it local on node)
    path: /datadisk/pihole/etc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-dnsmasq
spec:
  accessModes:
    - ReadWriteMany              # define how volume should be mounted on host (ReadOnlyMany , readWriteOnce, ReadWriteMany)
  capacity:
    storage: 20Gi
  hostPath:                     # volume path on host ( do not used in prod as it local on node)
    path: /datadisk/pihole/dnsmasq.d
