---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-etc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-dnsmasq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi