apiVersion: v1
kind: Service
metadata:
  name: pihole-service
namespace: pihole
spec:
  type: NodePort
  ports:
    - targetPort: 80             # port which we would like to reach on pod   IF WE DONT PROVIDE THIS VALUE WILL BE THE SAME AS IN PORT
      port: 80                   # port of service from service point of view   ITS NECEESARY
      nodePort: 8080             # port of Kube node - port we use eg in webbrowser
    - targetPort: 53
      port: 53
      protocol: TCP
    - targetPort: 53
      port: 53
      protocol: UDP
  selector:                      # selector to identify affected pods - labels the same as in pod
    app: pihole
